apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vk-paints-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/VK-Paints/vkpaints-helm-charts.git'
    targetRevision: main
    path: helm/vk-paints
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: vk-paints-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
