apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: vkpaints-nfs-sc
provisioner: nfs.csi.k8s.io
parameters:
  server: 10.0.1.159 # Change to your NFS Server IP
  share: /var/nfs/vkpaints
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.1

